server:
  port: 80

spring:
  application:
    name: spring-ai-deepseek-demo
  ai:
    openai:
      api-key: sk-xxxxxx    #  https://platform.deepseek.com  创建自己的APIkeys并充值 即可获得
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0
          #   temperature 参数默认为 1.0
          # 代码生成/数学解题	      0.0
          # 数据抽取/分析	      1.0
          # 通用对话		          1.3
          # 翻译	              1.3
          # 创意类写作/诗歌创作	  1.5

